#ifndef PRELUDE_UPDATER_VERSION_H
#define PRELUDE_UPDATER_VERSION_H

#define PRELUDE_UPDATER_VERSION "1.3.0"
#define PRELUDE_UPDATER_TAG     "v1.3.0"
#define PRELUDE_UPDATER_AUTHOR  "RadiantDelux"

#endif
