#ifndef PRELUDE_UPDATER_VERSION_H
#define PRELUDE_UPDATER_VERSION_H

#define PRELUDE_UPDATER_VERSION "1.4.0"
#define PRELUDE_UPDATER_TAG     "v1.4.0"
#define PRELUDE_UPDATER_AUTHOR  "RadiantDelux"

#endif
